version: '3'

services:
  postgresql:
    container_name: 'postgresql'
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    networks:
      - fundmatch


  backend:
    container_name: 'backend'
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: always
    env_file:
      - ./.env
    ports:
      - 8000:8000
    networks:
      - fundmatch


volumes:
  postgres-data:

networks:
  fundmatch:
    name: fundmatch