"""user_teams ondelete=cascade

Revision ID: 93a71210cc05
Revises: ab146b656b48
Create Date: 2023-06-24 18:06:25.626010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a71210cc05'
down_revision = 'ab146b656b48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_teams_team_id_fkey', 'user_teams', type_='foreignkey')
    op.drop_constraint('user_teams_user_id_fkey', 'user_teams', type_='foreignkey')
    op.create_foreign_key(None, 'user_teams', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_teams', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_teams', type_='foreignkey')
    op.drop_constraint(None, 'user_teams', type_='foreignkey')
    op.create_foreign_key('user_teams_user_id_fkey', 'user_teams', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_teams_team_id_fkey', 'user_teams', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
