"""Add unique contribution

Revision ID: 0bb347be7806
Revises: 2e90e85cd0d9
Create Date: 2023-06-25 17:10:20.310628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb347be7806'
down_revision = '2e90e85cd0d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contributions', ['user_id', 'event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contributions', type_='unique')
    # ### end Alembic commands ###
